// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TodoApi.Data;

#nullable disable

namespace TodoApi.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20251005111823_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TodoApi.Models.TodoTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Task");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 5, 11, 18, 20, 384, DateTimeKind.Utc).AddTicks(634),
                            Description = "Buy books for the next school year",
                            IsCompleted = false,
                            Priority = 0,
                            Title = "Buy books"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 5, 11, 18, 20, 384, DateTimeKind.Utc).AddTicks(637),
                            Description = "Need to clean the bed room",
                            IsCompleted = false,
                            Priority = 0,
                            Title = "Clean home"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 5, 11, 18, 20, 384, DateTimeKind.Utc).AddTicks(639),
                            Description = "Finish the mid-term assignment",
                            IsCompleted = false,
                            Priority = 0,
                            Title = "Takehome assignment"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 5, 11, 18, 20, 384, DateTimeKind.Utc).AddTicks(641),
                            Description = "Plan the soft ball cricket match on next Sunday",
                            IsCompleted = false,
                            Priority = 0,
                            Title = "Play Cricket"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 5, 11, 18, 20, 384, DateTimeKind.Utc).AddTicks(643),
                            Description = "Saman need help with his software project",
                            IsCompleted = false,
                            Priority = 0,
                            Title = "Help Saman"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 10, 5, 11, 18, 20, 384, DateTimeKind.Utc).AddTicks(645),
                            Description = "Schedule a check-up appointment for next month",
                            IsCompleted = false,
                            Priority = 1,
                            Title = "Call Dentist"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 10, 5, 11, 18, 20, 384, DateTimeKind.Utc).AddTicks(646),
                            Description = "Need to buy milk, bread, and eggs",
                            IsCompleted = false,
                            Priority = 2,
                            Title = "Grocery Shopping"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 10, 5, 11, 18, 20, 384, DateTimeKind.Utc).AddTicks(648),
                            Description = "Complete the first two chapters of the online course",
                            IsCompleted = false,
                            Priority = 0,
                            Title = "Learn Python"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
